name = "PoofAI"
uid = "poofai27-v001-55b4-92b6-64398e7ge43f"
version = 1
copyright = "MIT License"
description = "First Ai"
author = "Sep, Maudlin27"
url = ""
icon = ""
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
