---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 08/05/2024 22:34
---
local PoofBrain = import('/mods/PoofAI/lua/AI/PoofBrain.lua')
keyToBrain = keyToBrain or { }
keyToBrain['poofai'] = PoofBrain.NewAIBrain -- <- make sure import path points to the brain instance
keyToBrain['poofaicheat'] = PoofBrain.NewAIBrain -- <- make sure import path points to the brain instance